#!/bin/bash -l
#PBS -N mdQ_aug
#PBS -A UMIC0069
#PBS -l select=1:ncpus=32:mem=150GB
#PBS -l walltime=24:00:00
#PBS -j oe
#PBS -q casper

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

### Load modules required to run the job
module load intel peak_memusage
# module load conda
# conda activate my-npl-tf
module load ncarenv python/3.7.9
ncar_pylib

### Run program
peak_memusage.exe python runNoRH.py &> run_noRH.out

### Deactivate NCAR PyLib
deactivate
